---

- name: Update packages
  sudo: yes
  apt: update_cache=yes upgrade=yes

- name: Install nginx
  sudo: yes
  apt: pkg=nginx state=latest

- name: Remove existing default symlink
  sudo: yes
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Put nginx vhost config in place
  sudo: yes
  template: src=site_vhost.conf.j2 dest="/etc/nginx/sites-available/{{ site_name }}"

- name: Create symlink to enable site
  sudo: yes
  file: src="/etc/nginx/sites-available/{{ site_name }}"
        dest="/etc/nginx/sites-enabled/{{ site_name }}"
        state=link

- name: restart nginx
  service: name=nginx state=restarted
