---

- hosts: main_box
  tasks:
    - name: Clone the app repo
      sudo: yes
      git: repo={{ git_repo }}
           dest={{ deploy_dir }}
           accept_hostkey=yes
           key_file=/home/admin/.ssh/id_rsa
           version=master
           force=yes

    - name: Make send_emails.sh executable
      file: path={{ server_dir }}/send_email.sh mode=0755

    - name: Install pip dependencies
      sudo: yes
      command: "{{ virtualenv_name }}/bin/pip install -r requirements.txt chdir={{ bottle_deploy_dir }}"

    - name: Restart uwsgi
      sudo: yes
      service: name=uwsgi state=restarted
