---

  - name: Install bottle dependencies
    apt: pkg={{ item }} state=latest
    sudo: yes
    with_items:
      - python-software-properties
      - virtualenv
      - python2.7
      - python-pip
      - uwsgi
      - uwsgi-plugin-python

  - name: Install virtualenv
    sudo: yes
    command: pip install virtualenv

  - name: Make virtualenv
    sudo: yes
    command: virtualenv {{ virtualenv_name }}
      chdir={{ bottle_deploy_dir }}

  - name: Install bottle
    sudo: yes
    command: {{ virtualenv_name }}/bin/pip install bottle
      chdir={{ bottle_deploy_dir }}
