---

- name: Update apt-cache
  sudo: yes
  apt: update_cache=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install dependencies
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - python-software-properties
    - python-apt
    - python
    - g++
    - make
    - git
